### ISSUE TITLE
[Receber Carga] Checklist da carga enviada

### ISSUE THREAD

**Issue by ecmeirelles** [BeagleBox/react-app#10]
## Contexto:
Quando o usuário clicar em 'Receber Carga' na barra superior, o mesmo deve ser redirecionado a uma página contendo ações para receber a carga enviada. Uma dessas ações é a checagem dos itens enviados, onde o usuário deverá marcar como recebido ou não.

## Objetivo:
Implementar um checklist com ações de recebimento e não recebimento da carga.

## Critérios de aceitação:
- [ ] Deve haver uma lista com os itens enviados.
- [ ] Em cada item, deve haver um ícone de **recebido**.
- [ ] Em cada item, deve haver um ícone de **não recebido**.
